version: "3.9"

services:

  yandex-tank:
    image: direvius/yandex-tank
    container_name: tank
    entrypoint: /bin/bash
    volumes:
      - ./yandex_tank:/var/loadtest
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx

  goaccess:
    image: allinurl/goaccess
    container_name: goaccess
    restart: unless-stopped
    ports:  
      - "7890:7890"
    volumes:
      - ./nginx/logs:/logs
    command: "/logs/access.log -o /logs/report.html --log-format=COMBINED --real-time-html"

  app:
    build: ./app
    container_name: app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app