version: "3.9"

services:

  yandex-tank:
    image: direvius/yandex-tank
    container_name: tank
    entrypoint: /bin/bash
    volumes:
      - ./yandex_tank:/var/loadtest
    stdin_open: true
    tty: true
    networks:
      - priv_net
      
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    networks:
      - priv_net

  goaccess:
    image: allinurl/goaccess
    container_name: goaccess
    restart: unless-stopped
    ports:
      - "7890:7890"
    volumes:
      - ./nginx/logs:/logs
    command: "/logs/access.log -o /logs/report.html --log-format=COMBINED --real-time-html"
    networks:
      - priv_net

# Python App (3 instances)
  app1:
    build: ./app
    container_name: app1
    hostname: app1
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
    networks:
      - priv_net

  app2:
    build: ./app
    container_name: app2
    hostname: app2
    restart: unless-stopped
    ports:
      - "5002:5000"
    volumes:
      - ./app:/app
    networks:
      - priv_net

  app3:
    build: ./app
    container_name: app3
    hostname: app3
    restart: unless-stopped
    ports:
      - "5003:5000"
    volumes:
      - ./app:/app
    networks:
      - priv_net

networks:
  priv_net: {}